"""initial schema: funds, assets, fund_holdings, fund_nav, fund_asset_movements, ingestion_log

Revision ID: 0eb358255785
Revises: 
Create Date: 2026-07-09 23:58:59.491701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb358255785'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=True)
    op.create_table('funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fund_class_type', sa.String(length=50), nullable=True),
    sa.Column('manager_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_cnpj'), 'funds', ['cnpj'], unique=True)
    op.create_table('ingestion_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('ref_date', sa.Date(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_asset_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('ref_date', sa.Date(), nullable=False),
    sa.Column('prior_ref_date', sa.Date(), nullable=True),
    sa.Column('classification', sa.Enum('NEW', 'INCREASED', 'DECREASED', 'CLOSED', 'UNCHANGED', name='movement_classification'), nullable=False),
    sa.Column('qty_current', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('qty_prior', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('value_current', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('value_prior', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('qty_delta', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('value_delta', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('pct_delta', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'asset_id', 'ref_date', name='uq_movements_fund_asset_month')
    )
    op.create_index(op.f('ix_fund_asset_movements_asset_id'), 'fund_asset_movements', ['asset_id'], unique=False)
    op.create_index(op.f('ix_fund_asset_movements_fund_id'), 'fund_asset_movements', ['fund_id'], unique=False)
    op.create_index('ix_movements_asset_refdate', 'fund_asset_movements', ['asset_id', 'ref_date'], unique=False)
    op.create_index('ix_movements_classification_refdate', 'fund_asset_movements', ['classification', 'ref_date'], unique=False)
    op.create_index('ix_movements_fund_refdate', 'fund_asset_movements', ['fund_id', 'ref_date'], unique=False)
    op.create_table('fund_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('ref_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('source_file', sa.String(length=120), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'asset_id', 'ref_date', name='uq_fund_holdings_fund_asset_month')
    )
    op.create_index(op.f('ix_fund_holdings_asset_id'), 'fund_holdings', ['asset_id'], unique=False)
    op.create_index('ix_fund_holdings_asset_refdate', 'fund_holdings', ['asset_id', 'ref_date'], unique=False)
    op.create_index(op.f('ix_fund_holdings_fund_id'), 'fund_holdings', ['fund_id'], unique=False)
    op.create_index('ix_fund_holdings_refdate', 'fund_holdings', ['ref_date'], unique=False)
    op.create_table('fund_nav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('ref_date', sa.Date(), nullable=False),
    sa.Column('net_asset_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'ref_date', name='uq_fund_nav_fund_month')
    )
    op.create_index(op.f('ix_fund_nav_fund_id'), 'fund_nav', ['fund_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_nav_fund_id'), table_name='fund_nav')
    op.drop_table('fund_nav')
    op.drop_index('ix_fund_holdings_refdate', table_name='fund_holdings')
    op.drop_index(op.f('ix_fund_holdings_fund_id'), table_name='fund_holdings')
    op.drop_index('ix_fund_holdings_asset_refdate', table_name='fund_holdings')
    op.drop_index(op.f('ix_fund_holdings_asset_id'), table_name='fund_holdings')
    op.drop_table('fund_holdings')
    op.drop_index('ix_movements_fund_refdate', table_name='fund_asset_movements')
    op.drop_index('ix_movements_classification_refdate', table_name='fund_asset_movements')
    op.drop_index('ix_movements_asset_refdate', table_name='fund_asset_movements')
    op.drop_index(op.f('ix_fund_asset_movements_fund_id'), table_name='fund_asset_movements')
    op.drop_index(op.f('ix_fund_asset_movements_asset_id'), table_name='fund_asset_movements')
    op.drop_table('fund_asset_movements')
    op.drop_table('ingestion_log')
    op.drop_index(op.f('ix_funds_cnpj'), table_name='funds')
    op.drop_table('funds')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
