"""add insider_trades and alerts tables

Revision ID: 320cb7ee8c65
Revises: bef8ea193c2a
Create Date: 2026-07-10 04:05:05.591923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320cb7ee8c65'
down_revision: Union[str, None] = 'bef8ea193c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('ref_date', sa.Date(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=300), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_alerts_dedupe_key')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_ref_date'), 'alerts', ['ref_date'], unique=False)
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    op.create_table('insider_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('cnpj_companhia', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=True),
    sa.Column('tipo_empresa', sa.String(length=20), nullable=True),
    sa.Column('empresa', sa.String(length=255), nullable=True),
    sa.Column('tipo_cargo', sa.String(length=60), nullable=True),
    sa.Column('tipo_movimentacao', sa.String(length=80), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('tipo_operacao', sa.String(length=10), nullable=True),
    sa.Column('tipo_ativo', sa.String(length=80), nullable=True),
    sa.Column('caracteristica_valor_mobiliario', sa.String(length=60), nullable=True),
    sa.Column('intermediario', sa.String(length=200), nullable=True),
    sa.Column('data_movimentacao', sa.Date(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('preco_unitario', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_trades_cnpj_companhia'), 'insider_trades', ['cnpj_companhia'], unique=False)
    op.create_index('ix_insider_trades_cnpj_date', 'insider_trades', ['cnpj_companhia', 'data_movimentacao'], unique=False)
    op.create_index(op.f('ix_insider_trades_company_name'), 'insider_trades', ['company_name'], unique=False)
    op.create_index('ix_insider_trades_source_year', 'insider_trades', ['source_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_insider_trades_source_year', table_name='insider_trades')
    op.drop_index(op.f('ix_insider_trades_company_name'), table_name='insider_trades')
    op.drop_index('ix_insider_trades_cnpj_date', table_name='insider_trades')
    op.drop_index(op.f('ix_insider_trades_cnpj_companhia'), table_name='insider_trades')
    op.drop_table('insider_trades')
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_ref_date'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
