"""add asset_price_history table

Revision ID: 5ca8e7d44e60
Revises: fef75e8742d4
Create Date: 2026-07-12 00:34:33.239716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca8e7d44e60'
down_revision: Union[str, None] = 'fef75e8742d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'trade_date', name='uq_asset_price_ticker_date')
    )
    op.create_index(op.f('ix_asset_price_history_ticker'), 'asset_price_history', ['ticker'], unique=False)
    op.create_index(op.f('ix_asset_price_history_trade_date'), 'asset_price_history', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_price_history_trade_date'), table_name='asset_price_history')
    op.drop_index(op.f('ix_asset_price_history_ticker'), table_name='asset_price_history')
    op.drop_table('asset_price_history')
    # ### end Alembic commands ###
