"""widen pct_delta precision to avoid numeric overflow

Revision ID: 63ffcb209a91
Revises: 0eb358255785
Create Date: 2026-07-10 00:10:38.424416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ffcb209a91'
down_revision: Union[str, None] = '0eb358255785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fund_asset_movements', 'pct_delta',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fund_asset_movements', 'pct_delta',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
