"""add company_buybacks table

Revision ID: bef8ea193c2a
Revises: d2f35d114b21
Create Date: 2026-07-10 03:10:04.181560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef8ea193c2a'
down_revision: Union[str, None] = 'd2f35d114b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_buybacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('declared_at', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('operation_type', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('qty_common_shares', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('qty_preferred_shares', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_buybacks_cnpj'), 'company_buybacks', ['cnpj'], unique=False)
    op.create_index(op.f('ix_company_buybacks_company_name'), 'company_buybacks', ['company_name'], unique=False)
    op.create_index(op.f('ix_company_buybacks_declared_at'), 'company_buybacks', ['declared_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_buybacks_declared_at'), table_name='company_buybacks')
    op.drop_index(op.f('ix_company_buybacks_company_name'), table_name='company_buybacks')
    op.drop_index(op.f('ix_company_buybacks_cnpj'), table_name='company_buybacks')
    op.drop_table('company_buybacks')
    # ### end Alembic commands ###
