"""add fund_quota table (Informe Diario)

Revision ID: d2f35d114b21
Revises: 63ffcb209a91
Create Date: 2026-07-10 01:24:42.506552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f35d114b21'
down_revision: Union[str, None] = '63ffcb209a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_quota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('ref_date', sa.Date(), nullable=False),
    sa.Column('quota_value', sa.Numeric(precision=24, scale=12), nullable=False),
    sa.Column('net_asset_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('n_shareholders', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'ref_date', name='uq_fund_quota_fund_month')
    )
    op.create_index(op.f('ix_fund_quota_fund_id'), 'fund_quota', ['fund_id'], unique=False)
    op.create_index(op.f('ix_fund_quota_ref_date'), 'fund_quota', ['ref_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_quota_ref_date'), table_name='fund_quota')
    op.drop_index(op.f('ix_fund_quota_fund_id'), table_name='fund_quota')
    op.drop_table('fund_quota')
    # ### end Alembic commands ###
