"""add company_securities table

Revision ID: fef75e8742d4
Revises: 320cb7ee8c65
Create Date: 2026-07-10 05:00:42.214282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef75e8742d4'
down_revision: Union[str, None] = '320cb7ee8c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj_companhia', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('valor_mobiliario', sa.String(length=100), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj_companhia', 'ticker', name='uq_company_securities_cnpj_ticker')
    )
    op.create_index(op.f('ix_company_securities_cnpj_companhia'), 'company_securities', ['cnpj_companhia'], unique=False)
    op.create_index(op.f('ix_company_securities_ticker'), 'company_securities', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_securities_ticker'), table_name='company_securities')
    op.drop_index(op.f('ix_company_securities_cnpj_companhia'), table_name='company_securities')
    op.drop_table('company_securities')
    # ### end Alembic commands ###
